language: csharp
solution: ASPVulnerableLab.sln
env:
  global:
  - secure: IO2St6esLt8IIlx8KnMFUyX1kyS2SI1JxHtyWwzvM8yNOcfPQ3NPhKc9FZwRcc+t6EwNyyYfRpo64a0JIVYKRj4Je/T/BpUv395sz3LhVa+jjEyc3WMqqFdpOgn931mzbxItz+MH1an2NLdXFPqyPSAJSgHeXk/8s8PDQt7SmORGO7k3kV9PcBtcpmn3ZRiLTyKYU03S2prd+UHNN5rSxAby+K7i2IYuVTZXoH0+4gziu5F/w+nPGwByltUtWpAmO0mMU2IXoGFOPnsSpEiQ/y1t3slRBZ1YWXzzZDwvoytGbfFIG+UMNbvuxSwcpNvRDX8Etrs1D/ToS24nQvow0vzbdJ+kyvdaeE/n65rAo8sMSgf0ZGpEcaYtMWuYZzmdcgKigkIDcQAysZJWFPx8FfAP9MF16RJmpoUtamvzis9zJ3Gvxu1H4KPKrPkdoy6IEabfzJqlNqsSAqpGO8Eop63BS1JcEVyqixgBJBtfoVof7nBHw1CoAwZdE3eN4/CPipjYa3ChBZlUQy2LalFYG9uvjGlDcJkNN3bdbX2le7E8wzl+UAZh3Q2zfF+SOJ74P3L/TM4VfWpPfSI4uf5dnUtOSHymaJ3Hztb0XKtrt2VVjprZhLL/hMzEcIwDoTl5G1rp+Ot4D4ziNrNP+GfurtjXs33aHFSoReIaXw5R+fM=
addons:
  coverity_scan:
    project:
      name: "njacostac/ASPVulnerableLab"
      description: "<Your project description here>"
    notification_email: njacostac@hotmail.com
    build_command_prepend: ''
    build_command: msbuild /p:Configuration=Release /t:Rebuild ASPVulnerableLab.sln
    branch_pattern: master
